### ISSUE TITLE
Hi, when to release break 0.4.0 to rubygems? i saw you add changelog for 0.4.0 almost half years ago.

### ISSUE THREAD

**Issue by zw963** [gsamokovarov/break#14]
Thank you.

**Comment by zw963** [comment]
My own gem pryx dependent break, but, the break remote pry extension, make remote pry almost not work, because it only can be intercept the first time, then, because break cause remote-pry can't exit normally, remote pry port can't be connect to anymore.

I try to override the `lib/break/pry/extensions.rb` with my own version use $LOAD_PATH.unshift hack, but, never work, because
your use many `require_relative "./???"` instead of normally `require`.

this cause i almost have to copy all break gem into my gem, as if this gem is not maintained, though, i still not do like this, if you can release the latest break to rubygems, will be grateful.

**Comment by gsamokovarov** [comment]
Oh, man... sorry for that. I have released it to RubyGems today.
