### ISSUE TITLE
Not working for Ruby 3.0.0.

### ISSUE THREAD

**Issue by zw963** [gsamokovarov/break#6]
Following is a screenshot, thank you.

![image](https://user-images.githubusercontent.com/549126/113278455-854d5980-9314-11eb-9c6d-a2cd243e807f.png)

**Comment by gsamokovarov** [comment]
Should be fixed in `0.30.0`. Sorry for taking so long to respond and feel free to reopen the issue if the problem persists.

**Comment by zw963** [comment]
it works, thank you!
