### ISSUE TITLE
`next` performs `step` instead?

### ISSUE THREAD

**Issue by markokajzer** [gsamokovarov/break#7]
Hello and thanks a bunch for this project!

I am trying to switch our project to this gem after realizing too late that Zeitwerk does not support `byebug`.

I am having a little bit of trouble however, namely it seems like `next` and `step` do the exact same thing.

#### next

![Screen Shot 2021-05-21 at 09 21 16](https://user-images.githubusercontent.com/9379317/119098371-0c19db00-ba16-11eb-896d-b71d6606f975.png)

#### step

![Screen Shot 2021-05-21 at 09 21 35](https://user-images.githubusercontent.com/9379317/119098390-11772580-ba16-11eb-9ad9-4084ebf4994c.png)

This is a bit unfortunate as it would be really helpful to be able to step **over** some of these statements for debugging. Have you seen this before? Could some other gem be potentially interfering with `break` or something like that? We are on Ruby 2.7.2 using standard MRI.

**Comment by taylorthurlow** [comment]
I also have this problem.

**Comment by gsamokovarov** [comment]
I is broken at least for Ruby 2.7+. Too much life is happening to me right now, and I'm slow on the `break` side. A new official ruby debugger is in the works and you may keep an eye on it: https://github.com/ruby/debug. I'll at least try to take a look here, but I cannot promise a timely fix.

I'm really sorry, folks! ✌️

**Comment by taylorthurlow** [comment]
@gsamokovarov All good, thanks so much for the update.

**Comment by gsamokovarov** [comment]
Should be fixed in `0.30.0`. Sorry for taking so long to respond and feel free to reopen the issue if the problem persists.
