### ISSUE TITLE
break/pry/extensions.rb pry-remote hack cause pry-remote could not exit correctly.

### ISSUE THREAD

**Issue by zw963** [gsamokovarov/break#9]
Following is some screenshot for describe this issue:

1. I start a server use `puma`.
2.  visit this site with `GET /movies/infinity-war`
3. pry-remote get active like this:
![image](https://user-images.githubusercontent.com/549126/124393945-a6688080-dd2f-11eb-9db1-4ae1a14888b6.png)

4. run pry-remote command, it works, a REPL is attaching into current terminal, break work as expected.
![image](https://user-images.githubusercontent.com/549126/124393979-cbf58a00-dd2f-11eb-9b9b-63b55c7f5c39.png)

5.  run exit or pressing `Ctrl+D` to try to exit REPL, current server will continue run, but, current run pry-remote command terminal can not detached from terminal.
![image](https://user-images.githubusercontent.com/549126/124394063-36a6c580-dd30-11eb-9042-1d40f161e988.png)

6. If press `Ctrl+C` to exit this REPL forcely, will cause DRb server broken, e.g. when visit above same url again, will get following error msg.

```
2021-07-05 01:29:51 +0800 Rack app ("GET /movies/infinity-war" - (127.0.0.1)): #<DRb::DRbConnError: druby://127.0.0.1:38385 - #<Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 38385>>
```

i guess this issue caused by DRb client can not correct close the connection with DRb server, all have to do is, restart puma server again.

## some thoughts for how to fix?

We have to trap `Ctrl+C` to handle correct disconnect with remote DRb server. as following log does.

```
[pry-remote] Remote session terminated
[pry-remote] Ensure stop service
```

Or, we need hack ruby `exit` method to correct handle this.

Thank you.

**Comment by zw963** [comment]
Anyway, i consider this core ext is prepend to pry-remote to change it behavior unexpectedly when we only `require 'break' ` is not appropriated.  only personal opinion.

**Comment by gsamokovarov** [comment]
Thanks for the report, I have noticed that as well. The pry-remote integration is pretty hacky as it is, we'll look into how I can improve it.

**Comment by zw963** [comment]
> Thanks for the report, I have noticed that as well. The pry-remote integration is pretty hacky as it is, will look into how I can improve it.

The simplest solution(maybe not a solution) is, separate `pry-remote` extensions to a new file,  and not require this hack automatically if user only want `require 'break'`. if they want, then can require it manually at any time.

**Comment by gsamokovarov** [comment]
I have made the `pry-remote` integration optional. It needs to be activated with manual require of `break/remote`.

**Comment by zw963** [comment]
> I have made the `pry-remote` integration optional. It needs to be activated with manual require of `break/remote`.

When to release break 0.4.0 ? anyway, we need install it from rubygems, not github repo, thank you.
